1) Clean the dataset look and study the dataset for this part

2) Create a Dictionary with the 10 countries that have the most 'Quantity' ordered except UK

3)  Find Total Sale between two dates entered

4) Find each Countries Total SALE to find which Countries is highest potential customer

5) Which Customer Id has highest purchase in quantity and total and find out the country of it

6) Which Customer Id has lowest purchase in quantity and total and find out the country of it

7) Find the biggest order In Sale (Cost) which country was the order from and fiind total purchase (Cost) done by that customer ID

8) Find how many different customers are available for each country save the count in dictionary also return countries with highest and lowest customer count

9) Find which stock code was ordered the most by each country

In [3]:
import pandas as pd

In [4]:
path = '/content/Online_Retail.csv'
df = pd.read_csv('Online_Retail(2).csv', encoding = "ISO-8859-1")
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/11 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/11 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/11 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/11 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/11 12:50,4.95,12680.0,France

In [5]:
df.shape

(541909, 8)

1) Clean the dataset look and study the dataset for this part

In [8]:
df[df['Quantity'] < 0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,12/1/10 9:41,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,12/1/10 9:49,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,12/1/10 10:24,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,12/1/10 10:24,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,12/1/10 10:24,0.29,17548.0,United Kingdom

In [7]:
df[df['UnitPrice'] < 0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,8/12/11 14:51,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,8/12/11 14:52,-11062.06,NaN,United Kingdom

In [6]:
df[df['UnitPrice'] == 0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,12/1/10 11:52,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,12/1/10 14:32,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,12/1/10 14:33,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,12/1/10 14:33,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,12/1/10 14:34,0.0,NaN,United Kingdom

In [9]:
# Drop rows where 'Quantity' and Unit Price is negative
df = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)]
print(df)
df.shape

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

          InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/10 8:26       2.55     17850.0  United Kingdom
1        12/1/10 8:26       3.39     17850.0  United Kingdom
2        12/1/10 8:26       2.75     17850.0  United Kingdom
3        12/1/10 8:26       3.39     17850.0  United Kingdom
4        12/1/10 8:26       3.39     17850.0  United Kingdom
...               ...        ...         ...             ...
541904  12/9/11 12:50       0.85     12680.0          France
541905  12/9/11 12:50       2.10     12680.0          France
541906  12/9/11 12:50       4.15     12680.0          France
541907  12/9/11 12:50       4.15     12680.0          France
541908  12/9/11 12:50       4.95     12680.0          France

[530104 rows x 8 columns]

(530104, 8)

In [11]:
# Extract the first 5 digits from the StockCode column and overwrite the original column
df['StockCode'] = df['StockCode'].str[:5]
print(df)
df.shape

       InvoiceNo StockCode                          Description  Quantity  \
0         536365     85123   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365     84406       CREAM CUPID HEARTS COAT HANGER         8
3         536365     84029  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365     84029       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

          InvoiceDate  UnitPrice  CustomerID         Country
0        12/1/10 8:26       2.55     17850.0  United Kingdom
1        12/1/10 8:26       3.39     17850.0  United Kingdom
2        12/1/10 8:26       2.75     17850.0  United Kingdom
3        12/1/10 8:26       3.39     17850.0  United Kingdom
4        12/1/10 8:26       3.39     17850.0  United Kingdom
...               ...        ...         ...             ...
541904  12/9/11 12:50       0.85     12680.0          France
541905  12/9/11 12:50       2.10     12680.0          France
541906  12/9/11 12:50       4.15     12680.0          France
541907  12/9/11 12:50       4.15     12680.0          France
541908  12/9/11 12:50       4.95     12680.0          France

[530104 rows x 8 columns]

<ipython-input-11-ade29e8e89fb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['StockCode'] = df['StockCode'].str[:5]

(530104, 8)

In [12]:
# Check for missing values in the 'StockCode' column and remove rows with NaN values
df = df.dropna(subset=['StockCode'])

# Filter out rows where StockCode is entirely a string
df = df[df['StockCode'].str.isnumeric()]

df.reset_index(drop=True, inplace=True)
df.shape

(527725, 8)

In [13]:
#2) Create a Dictionary with the 10 countries that have the most 'Quantity' ordered except UK

df_exceptUK = df[df['Country'] != 'United Kingdom']

quant = df_exceptUK.groupby('Country')['Quantity'].sum()

# Get the top 10 countries with the most 'Quantity' ordered
top_10_countries = quant.nlargest(10)

# Convert the top 10 countries Series to a dictionary
top_10_countries_dict = top_10_countries.to_dict()

# Display the dictionary
print(top_10_countries_dict)

{'Netherlands': 200258, 'EIRE': 147062, 'Germany': 118139, 'France': 111269, 'Australia': 83900, 'Sweden': 36042, 'Switzerland': 30527, 'Spain': 27731, 'Japan': 26016, 'Belgium': 22962}

In [69]:
# 3) Find Total Sale between two dates entered

import datetime
# Convert 'InvoiceDate' to datetime format
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], format='%m/%d/%y %H:%M')

# Input start and end dates from the user
start_date_input = input("Enter the start date (MM/DD/YY): ")
end_date_input = input("Enter the end date (MM/DD/YY): ")

# Convert user input to datetime format
start_date = pd.to_datetime(start_date_input, format='%m/%d/%y')
end_date = pd.to_datetime(end_date_input, format='%m/%d/%y')

# Filter the DataFrame for the user-defined date range
filtered_df = df[(df['InvoiceDate'] >= start_date) & (df['InvoiceDate'] <= end_date)]

# Calculate the total sale by summing the product of 'Quantity' and 'UnitPrice'
total_sale = (filtered_df['Quantity'] * filtered_df['UnitPrice']).sum()

print(f"Total Sale between {start_date.date()} and {end_date.date()}: ${total_sale:.2f}")

Enter the start date (MM/DD/YY): 12/1/10
Enter the end date (MM/DD/YY): 12/2/10
Total Sale between 2010-12-01 and 2010-12-02: $57626.33

In [32]:
#4) Find each Countries Total SALE to find which Countries is highest potential customer

# Calculating total sale
df['TotalSale'] = df['Quantity'] * df['UnitPrice']

# Group by 'Country' and calculating the total sale for each country
country_total_sales = df.groupby('Country')['TotalSale'].sum().reset_index()

# Finding the country with the highest total sale
highest_potential_customer = country_total_sales.loc[country_total_sales['TotalSale'].idxmax()]

# Display the total sales for each country and the highest potential customer
print("Total Sales by Country:")
print(country_total_sales.sort_values(by=['TotalSale'], ascending=False).head())
print("\nCountry with the Highest Total Sale:")
print(highest_potential_customer)

Total Sales by Country:
           Country   TotalSale
36  United Kingdom  8747163.21
24     Netherlands   283889.34
10            EIRE   271164.30
14         Germany   205569.89
13          France   184582.74

Country with the Highest Total Sale:
Country      United Kingdom
TotalSale        8747163.21
Name: 36, dtype: object

In [43]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalSale
0,536365,85123,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom,20.34
2,536365,84406,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom,22.00
3,536365,84029,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom,20.34
4,536365,84029,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
527720,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/11 12:50,0.85,12680.0,France,10.20
527721,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/11 12:50,2.10,12680.0,France,12.60
527722,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/11 12:50,4.15,12680.0,France,16.60
527723,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/11 12:50,4.15,12680.0,France,16.60
527724,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/11 12:50,4.95,12680.0,France,14.85

In [41]:
# 5) Which Customer Id has highest purchase in quantity and total and find out the country of it

# Groupby 'CustomerID' and calculate the total quantity for each customer
customer_highest_quantity = df.groupby('CustomerID')['Quantity'].sum().reset_index()

# Find the customer with the highest total sale
highest_purchase_customerID = customer_highest_quantity.loc[customer_highest_quantity['Quantity'].idxmax()]

# Find the country of the customer with the highest purchase in quantity
country_of_highest_purchase_customer = df[df['CustomerID'] == highest_purchase_customerID['CustomerID']]['Country'].iloc[0]

# Display the total sales for each country and the highest potential customer
print("Quantity Total by Customer:")
print(customer_highest_quantity.sort_values(by=['Quantity'], ascending=False).head())
print("\nCustomer with the Highest Purchase:")
print(highest_purchase_customerID)
print('\nCustomer Country:', country_of_highest_purchase_customer)

Quantity Total by Customer:
      CustomerID  Quantity
1689     14646.0    196844
3006     16446.0     80997
1879     14911.0     80179
55       12415.0     77373
0        12346.0     74215

Customer with the Highest Purchase:
CustomerID     14646.0
Quantity      196844.0
Name: 1689, dtype: float64

Customer Country: Netherlands

In [43]:
#6) Which Customer Id has lowest purchase in quantity and total and find out the country of it

# Group by CustomerID and calculate the sum of Quantity for each customer
customer_quantity = df.groupby('CustomerID')['Quantity'].sum()

# Find the Customer ID with the lowest purchase in quantity
min_quantity_customer_id = customer_quantity.idxmin()

# Find the country of the customer with the lowest purchase in quantity
country_of_min_quantity_customer = df[df['CustomerID'] == min_quantity_customer_id]['Country'].iloc[0]

print("Quantity Total by Customer:")
print(customer_highest_quantity.sort_values(by=['Quantity'], ascending=False).head())
print("\nCustomer with the Lowest Purchase:")
print(min_quantity_customer_id)
print('\nCustomer Country:')
print(country_of_min_quantity_customer)

Quantity Total by Customer:
      CustomerID  Quantity
1689     14646.0    196844
3006     16446.0     80997
1879     14911.0     80179
55       12415.0     77373
0        12346.0     74215

Customer with the Lowest Purchase:
16257.0

Customer Country:
United Kingdom

In [46]:
#7) Find the biggest order In Sale (Cost) which country was the order from and fiind total purchase (Cost) done by that customer ID

# Group by InvoiceNo and calculate the total sale cost for each invoice
invoice_total_sale = df.groupby('InvoiceNo')['TotalSale'].sum()

# Find the invoice with the highest total sale cost
biggest_order_invoice = invoice_total_sale.idxmax()

# Find the country of the biggest order
country_of_biggest_order = df[df['InvoiceNo'] == biggest_order_invoice]['Country'].iloc[0]

# Calculate the total purchase cost done by the customer responsible for the biggest order
customer_id_of_biggest_order = df[df['InvoiceNo'] == biggest_order_invoice]['CustomerID'].iloc[0]
total_purchase_cost_by_customer = df[df['CustomerID'] == customer_id_of_biggest_order]['TotalSale'].sum()

print(f"Biggest order in Sale: {total_purchase_cost_by_customer:.2f}")
print(f"Biggest Order country: {country_of_biggest_order}.")
print(f"Therefore, the total purchase cost done by customer ID {customer_id_of_biggest_order} for the biggest order is {total_purchase_cost_by_customer:.2f}")

Biggest order in Sale: 168472.50
Biggest Order country: United Kingdom.
Therefore, the total purchase cost done by customer ID 16446.0 for the biggest order is 168472.50

In [55]:
#8) Find how many different customers are available for each country save the count in dictionary also return countries with highest and lowest customer count

# Group by 'Country' and calculate the count of unique 'CustomerID' values within each group
customer_counts_by_country = df.groupby('Country')['CustomerID'].nunique()

# Convert the result to a dictionary
customer_counts_dict = customer_counts_by_country.to_dict()

# Find countries with the highest and lowest customer counts
country_with_highest_customers = customer_counts_by_country.idxmax()
country_with_lowest_customers = customer_counts_by_country.idxmin()

# Print the dictionary and the countries with the highest and lowest customer counts
print("Customer Counts by Country:")
print(customer_counts_dict)
print()
print(f"Country with the highest customer count: {country_with_highest_customers}")
print(f"Country with the lowest customer count: {country_with_lowest_customers}")

Customer Counts by Country:
{'Australia': 9, 'Austria': 11, 'Bahrain': 2, 'Belgium': 25, 'Brazil': 1, 'Canada': 4, 'Channel Islands': 9, 'Cyprus': 8, 'Czech Republic': 1, 'Denmark': 9, 'EIRE': 3, 'European Community': 1, 'Finland': 12, 'France': 87, 'Germany': 94, 'Greece': 4, 'Hong Kong': 0, 'Iceland': 1, 'Israel': 3, 'Italy': 14, 'Japan': 8, 'Lebanon': 1, 'Lithuania': 1, 'Malta': 2, 'Netherlands': 9, 'Norway': 10, 'Poland': 6, 'Portugal': 19, 'RSA': 1, 'Saudi Arabia': 1, 'Singapore': 1, 'Spain': 30, 'Sweden': 8, 'Switzerland': 21, 'USA': 4, 'United Arab Emirates': 2, 'United Kingdom': 3916, 'Unspecified': 4}

Country with the highest customer count: United Kingdom
Country with the lowest customer count: Hong Kong

In [53]:
#9) Find which stock code was ordered the most by each country

# Group by 'Country' and 'StockCode', and calculate the count of each stock code within each country
most_ordered_stock = df.groupby(['Country', 'StockCode']).size().reset_index(name='OrderCount')

# Find the stock code with the highest order count for each country
most_ordered_stock = most_ordered_stock.sort_values(by=['Country', 'OrderCount'], ascending=[True, False])
most_ordered_stock = most_ordered_stock.groupby('Country').first().reset_index()

most_stocks = most_ordered_stock.sort_values(by='OrderCount', ascending=False)
print(most_stocks)
print()

print('The stock code that was ordered the most is:')
print(most_stocks.iloc[0])

                 Country StockCode  OrderCount
36        United Kingdom     85099        3681
14               Germany     22326         113
13                France     23084          74
10                  EIRE     22423          72
3                Belgium     22326          38
24           Netherlands     22629          28
12               Finland     84997          25
31                 Spain     22423          22
33           Switzerland     84997          21
27              Portugal     20725          14
6        Channel Islands     85099          13
25                Norway     22720          13
0              Australia     47590          12
16             Hong Kong     84997          11
19                 Italy     22720           9
9                Denmark     84997           9
7                 Cyprus     22423           8
26                Poland     16016           7
1                Austria     84997           7
32                Sweden     22720           7
17               Iceland     22375           6
20                 Japan     85032           6
23                 Malta     72807           6
30             Singapore     84997           6
18                Israel     23240           5
2                Bahrain     72802           4
34                   USA     84997           4
37           Unspecified     22150           4
5                 Canada     15044           3
4                 Brazil     15056           3
11    European Community     22312           2
22             Lithuania     15056           2
15                Greece     21700           2
28                   RSA     20676           1
29          Saudi Arabia     20781           1
8         Czech Republic     20972           1
35  United Arab Emirates     20961           1
21               Lebanon     21165           1

The stock code that was ordered the most is:
Country       United Kingdom
StockCode              85099
OrderCount              3681
Name: 36, dtype: object