In [ ]:
import pandas as pd

In [ ]:
path = '/content/Ch3_Q7_Data_File.xlsx'
df=pd.read_excel("Ch3_Q7_Data_File.xlsx")

In [ ]:
df.shape

(50, 8)

In [ ]:
df_cleaned = df.iloc[:, :3]
df_cleaned

    Rank           State  Life_Expectancy
0      1          Hawaii             81.5
1      2       Minnesota             80.9
2      3      California             80.4
3      4        New York             80.4
4      5     Connecticut             80.2
5      6   Massachusetts             80.1
6      7    North Dakota             80.1
7      8            Utah             80.1
8      9        Colorado             79.9
9     10         Arizona             79.9
10    11    South Dakota             79.9
11    12   New Hampshire             79.7
12    13         Vermont             79.7
13    14         Florida             79.7
14    15            Iowa             79.7
15    16      New Jersey             79.7
16    17      Washington             79.7
17    18       Wisconsin             79.3
18    19    Rhode Island             79.3
19    20           Idaho             79.2
20    21        Nebraska             79.2
21    22          Oregon             79.0
22    23        Illinois             78.8
23    24           Maine             78.7
24    25        Virginia             78.5
25    26          Kansas             78.4
26    27         Montana             78.4
27    28        Delaware             78.3
28    29          Alaska             78.3
29    30           Texas             78.3
30    31      New Mexico             78.2
31    32    Pennsylvania             78.2
32    33        Maryland             78.1
33    34        Michigan             77.9
34    35         Indiana             77.7
35    36         Wyoming             77.6
36    37          Nevada             77.6
37    38            Ohio             77.5
38    39        Missouri             77.4
39    40  North Carolina             77.2
40    41         Georgia             77.1
41    42  South Carolina             76.6
42    43       Tennessee             76.2
43    44        Kentucky             76.2
44    45        Arkansas             76.1
45    47        Oklahoma             75.6
46    48       Louisiana             75.4
47    49         Alabama             75.2
48    50   West Virginia             75.2
49    51     Mississippi             74.8

In [13]:
#Mean of Life Expectancy
df_cleaned['Life_Expectancy'].mean().round(2)

78.42

In [12]:
#Median of Life Expectancy
df_cleaned['Life_Expectancy'].median().round(2)

78.45